### ISSUE TITLE
Issues synching

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/ropsten#4]
I'm sorry I am not actually the one synching so I have no data for you, but I am cross posting from reddit:
https://www.reddit.com/r/ethereum/comments/63vd1l/these_ropsten_revived_instructions_do_not_seem_to/

**Comment by jgostylo** [comment]
Thanks for leaving this issue.  It seems that deleting chain data is not enough.  I had to delete the entire geth directory under /Users/<username>/Library/Ethereum/testnet.  When I started it again it still did not work (I was on the attacked chain).  One time I tried and I believe I was on the attacked chain but I could not sync the entire thing.  It was about 5-6 attempts of deleting the entire directory (and not just chaindata) and running again before my chain synced correctly.  I do not know why it worked the last time.

**Comment by cdetrio** [comment]
Syncing has shown to be a bit fragile when there are many peers on different forks. Deleting the chaindata is sufficient to start a fresh sync, but it seems there's some randomness in which chain you end up on (it depends on which peers you connect to).

There's a [troubleshooting section](https://github.com/ethereum/ropsten#troubleshooting) now, with instructions on how to force the client to connect to the right peers and thus sync to the right chain.

We'd still like to debug the issues causing fragility during the initial sync. You can help by capturing a debug log:

```
geth --vmodule=p2p=6,downloader=6 --testnet --fast --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303" 
```

**Comment by cdetrio** [comment]
@jgostylo It turns out that both`/Users/<username>/Library/Ethereum/testnet/geth/chaindata` **and** `/Users/<username>/Library/Ethereum/testnet/geth/nodes` should be deleted. The reasons is that if you previously had peers on the attacked chain, then those peers' enode URLs will be saved in `testnet/geth/nodes`. When geth starts it first tries to connect to those saved peers.

Another confusing issue is that bootnodes are only used for *node* discovery on the devp2p DHT. That is, when the client utilizes a bootstrap node it does NOT connect as a *peer* but only as a *node* for [devp2p node discovery](https://github.com/ethereum/devp2p/blob/master/rlpx.md#node-discovery), and all nodes share the same DHT regardless of what chain they are on. For the testnet, this is problematic because the majority of nodes on the DHT are on the mainnet. So what the client does is get random enode URLs through the DHT, and then attempts to open *peer* connections through the [wire protocol](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol) (the wire protocol is used to fetch headers and blocks and sync the chain). But most of those attempts will fail because they are peers on the mainnet, you'll see a "Genesis block mismatch" in the log:
```
TRACE[04-11|13:13:32] Protocol eth/63 failed                   id=017bb849684fe90e conn=dyndial err="Genesis block mismatch - d4e56740f876aef8 (!= 41941023680923e0)"
```
A recent update https://github.com/ethereum/go-ethereum/pull/13874 helps. With this update, if geth hasn't made a successful *peer* connection after 20 seconds (i.e. has not found a peer with the same genesis block), then it will try connecting directly to the bootnodes as peers.

**Comment by chfast** [comment]
In a new datadir synchronization does not start, but I noticed weird thing.

Is you set `--bootnodes` from command line it does not work. But if you set them by JS console (`admin.addPeer()`) or by `static-nodes.json` file it works imminently.

**Comment by cdetrio** [comment]
@chfast yeah that's what I was trying to explain. `--bootnodes` only sets the enode URL as a seed node for node discovery (devp2p DHT query). `admin.addPeer` and `static-nodes.json` cause the client to open a *peer* connection to an enode URL. There's a difference between a *node* (devp2p/DHT protocol only, no wire protocol messages) and a *peer* (wire protocol handshake).

**Comment by ulope** [comment]
It looks like the two recommended boot nodes (`6ce05930...` and `20c9ad97...`) have become broken too.

I've been unsuccessful in getting a fresh node to sync in the last few days even with the `--nodiscover`, `admin.addPeer()` method.

**Comment by cdetrio** [comment]
@ulope The bootnodes nodes are still up but they were at their peer limits, sorry. I've bumped up `--max-peers`, hopefully you can connect to them now.

**Comment by er3es** [comment]
Hello. It seems that I cannot connect to the peers. I was fully synced yesterday but today I get the following error

> DEBUG[10-25|10:23:19] Adding p2p peer                          id=6ce05930c72abc63 name=Parity/v1.8.0-unstab...                                              addr=13.84.180.240:30303 peers=1
> TRACE[10-25|10:23:19] Dial task done                           task="staticdial 6ce05930c72abc63 13.84.180.240:30303"
> TRACE[10-25|10:23:19] New dial task                            task="wait for dial hist expire (12.410515547s)"
> TRACE[10-25|10:23:19] Starting protocol eth/63                 id=6ce05930c72abc63 conn=staticdial
> DEBUG[10-25|10:23:19] Ethereum peer connected                  id=6ce05930c72abc63 conn=staticdial name=Parity/v1.8.0-unstable-9196c72-20170918/x86_64-linux-gnu/rustc1.20.0
> DEBUG[10-25|10:23:19] Ethereum handshake failed                id=6ce05930c72abc63 conn=staticdial err=EOF
> DEBUG[10-25|10:23:19] Removing p2p peer                        id=6ce05930c72abc63 conn=staticdial duration=10.060ms  peers=0 req=false err=EOF
> DEBUG[10-25|10:23:28] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
>

**Comment by denispeplin** [comment]
- removed `/home/den/.ethereum/testnet/`
- started `geth --testnet --fast --cache 2048 --nodiscover`
- executed `admin.addPeer('enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303')`
- executed `admin.addPeer('enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303')`

sync didn't start.
without all these tricks I ended up on broken network after about 900000 blocks.
hope geth will support `Kovan` some day, because `Ropsten` is permanently broken (tried about month ago, wasn't able to sync).

**Comment by jachiang** [comment]
+1 
(`6ce059`, `20c9ad` not working, success on `addPeer`, but `[]` on `admin.peers`)

**Comment by seaify** [comment]
+1
(6ce059, 20c9ad not working, success on addPeer, but [] on admin.peers)

**Comment by larcai** [comment]
+1

**Comment by jachiang** [comment]
...I just use parity now, which syncs. Geth to connect to ipc generated by parity.

**Comment by eelkevdbos** [comment]
+1

**Comment by quantumproducer** [comment]
+1, this is a major issue!

**Comment by nnbosko** [comment]
+1

**Comment by Braynid** [comment]
+1

**Comment by Bearil** [comment]
+1

**Comment by gernotpokorny** [comment]
+1

**Comment by arich-net** [comment]
+1
